### ISSUE TITLE
V8-8-0-Energy+.idd line 89660 

### ISSUE THREAD

**Issue by RuihangWang** [openergy/opyplus#49]
- **Opyplus Package Version**: 1.1.2
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**
Line 89660 with extra space will lead to match error
\ group Hybrid Model

**Expected behavior**
Remove the space
\group Hybrid Model

**Comment by geoffroy-destaintot** [comment]
I changed the regex that recognizes groups and it now recognizes "\ group" (whereas it only recognized "\group" before)
the fix is in release [v1.1.3](https://github.com/openergy/opyplus/releases/tag/v1.1.3)
